### ISSUE TITLE
throw exception at version 2.3.7

### ISSUE THREAD

**Issue by shts** [shts/NogiFeed#3]
throw Exception from 'PagerSlidingTabStrip' library.

11-29 13:21:09.376      624-624/shts.jp.android.nogifeed E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoSuchMethodError: android.view.ViewTreeObserver.removeOnGlobalLayoutListener
            at com.astuetz.PagerSlidingTabStrip$3.onGlobalLayout(PagerSlidingTabStrip.java:393)
            at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:549)
            at android.view.ViewRoot.performTraversals(ViewRoot.java:1189)
            at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)

ref. 

http://stackoverflow.com/questions/15162821/why-does-removeongloballayoutlistener-throw-a-nosuchmethoderror

https://github.com/jpardogo/PagerSlidingTabStrip/blob/master/library/src/com/astuetz/PagerSlidingTabStrip.java

**Comment by shts** [comment]
fixed.
